apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldapp-deployment
spec:
  selector:
    matchLabels:
      app: helloworldapp-pod
  template:
    metadata:
      labels:
        app: helloworldapp-pod
    spec:
      containers:
      - name: helloworldapp-container
        image: mibuks01.azurecr.io/helloworldapp:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80